version: '3.8'

services:
  postgres:
    container_name: think_backend
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root
      POSTGRES_DB: think_db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres